### PR TITLE
Improve version

### PR DESCRIPTION
**Pull request by chrisl8888**
Improve versions of dependancies

### CODE REVIEW

**Comment by JohannesHoppe** [comment]
Hello, thanks for your participation. But I’m confused about your updated version numbers. Do you have any real requirement for this change? All dependencies are prefixed with a circumflex. For example current package.json requires "opener": "^1.4.0". Right now this will download opener v1.4.1 anyway.

**Comment by chrisl8888** [comment]
I was hoping to update the node-inspector; i went ahead and updated all the latest versions. When using your plugin it uses the minimum 0.8.4 version. It for some reasons defaults to that version when i install / use your plugin. 

I thought by bumping up the numbers for node-inspector would solve this.

**Comment by JohannesHoppe** [comment]
Ok, why not? I will bump the versions!

**Comment by JohannesHoppe** [comment]
v0.0.3 is on npm now. please test!

**Pull request merged**
